name: RE_project_1
channels:
  - defaults
  - conda-forge
  - pytorch
  - dglteam
dependencies:
  - python=3.6
  - pytorch=
  - ipython>=7.9
  - torchvision
  - pillow<7.0 # version 7 breaks torchvision 0.4.2 and earlier
  - torchtext=0.4.0
  - cudatoolkit
  - matplotlib
  - scipy
  - numpy=1.16.6
  - scikit-learn
  - pandas
  - cython
  - rise
  - numba
  - spacy=2.2.2
  - nltk
  - ffmpeg>4.1
  - opencv
  - freetype>=2.10
  - dgl
  - graphviz
  - swig
  - tensorflow=1.12
  - bitarray
  - lmdb
  - clang
  - decorator
  - networkx
  - pygraphviz
  - tqdm
  - pip
  - pip:
      # spaCy models
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz
    - https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.2.5/de_core_news_sm-2.2.5.tar.gz
    - gym
    - atari-py
    - box2d-py
    - torchviz
    - angr
    - rouge==0.3.2
